use_frameworks!

platform :ios, '15.0'

target 'MotionAnalysisCamera_Example' do
  pod 'TensorFlowLiteSwift', '~> 2.10.0', :subspecs => ['CoreML', 'Metal']
  pod 'GoogleMLKit/PoseDetection', '3.2.0'
  pod 'KMLDataTypes', :git=> 'https://www.github.com/Kinetix-ML/KMLDataTypes'
  pod 'MotionAnalysisCamera', :path => '../'

  target 'MotionAnalysisCamera_Tests' do
    inherit! :search_paths

    #pod 'Quick', '~> 2.2.0'
    #pod 'Nimble', '~> 10.0.0'
    #pod 'FBSnapshotTestCase' , '~> 2.1.4'
    #pod 'Nimble-Snapshots' , '~> 9.4.0'
    
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        config.build_settings['SWIFT_VERSION'] = '5.8'
      end
    end
  end
end
